#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)
host = data.get("host")
LEAN_APP_URL  = f"https://{host}"
#This is specific to you module, so you need to change it accordingly.
rdb = agent.redis_connect(use_replica=True)
smtp_settings = agent.get_smarthost_settings(rdb)

SMTP_ENABLED = 'true' if smtp_settings['enabled'] else 'false'
SMTP_HOST = smtp_settings['host']
SMTP_PORT = smtp_settings['port']
SMTP_USERNAME = smtp_settings['username']
SMTP_PASSWORD = smtp_settings['password']
SMTP_ENCRYPTION = smtp_settings['encrypt_smtp']
SMTP_TLSVERIFY = '1' if smtp_settings['tls_verify'] else ''


lean_time = {
    "LEAN_EMAIL_RETURN": '',
    "LEAN_EMAIL_USE_SMTP": SMTP_ENABLED,
    "LEAN_EMAIL_SMTP_HOSTS": SMTP_HOST,
    "LEAN_EMAIL_SMTP_AUTH": 'true',
    "LEAN_EMAIL_SMTP_USERNAME": SMTP_USERNAME,
    "LEAN_EMAIL_SMTP_PASSWORD": SMTP_PASSWORD,
    "LEAN_EMAIL_SMTP_AUTO_TLS": SMTP_TLSVERIFY,
    "LEAN_EMAIL_SMTP_SECURE": SMTP_ENCRYPTION,
    "LEAN_EMAIL_SMTP_SSLNOVERIFY": 'false',
    "LEAN_EMAIL_SMTP_PORT": SMTP_PORT,
    "LEAN_APP_URL ": LEAN_APP_URL
}
agent.write_envfile("leantime.env", lean_time)
#agent.dump_env()
